---
env:
  jasmine: true
  node: true
  mocha: true
  browser: true
  builtin: true
globals:
  _: true
  angular: true
rules:
  block-scoped-var: error
  camelcase: off
  curly:
    - error
    - all
  dot-notation:
    - error
    -
      allowKeywords: true
  eqeqeq:
    - error
    - allow-null
  strict: off
  guard-for-in: error
  new-cap: error
  no-bitwise: error
  no-caller: error
  no-cond-assign:
    - error
    - except-parens
  no-debugger: error
  no-empty: error
  no-eval: error
  no-extend-native: error
  no-extra-parens: error
  no-irregular-whitespace: error
  no-iterator: error
  no-loop-func: error
  no-multi-str: error
  no-new: error
  no-plusplus: error
  no-proto: error
  no-script-url: error
  no-sequences: error
  no-shadow: error
  no-undef: error
  no-unused-vars: error
  no-with: error
  quotes:
    - error
    - single
  semi:
    - off
    - never
  valid-typeof: error
  wrap-iife:
    - error
    - inside
